date_format: '%d.%m.%Y' # формат даты: день.месяц.год
time_format: '%H:%M:%S' # формат времени: часы:минуты:секунды
number_format: '0,0.[00]' # формат чисел: разделитель тысяч - запятая, разделитель дробной части - точка, два знака после запятой
language_settings:
  months:
    - Январь
    - Февраль
    - Март
    - Апрель
    - Май
    - Июнь
    - Июль
    - Август
    - Сентябрь
    - Октябрь
    - Ноябрь
    - Декабрь
  weekdays:
    - Понедельник
    - Вторник
    - Среда
    - Четверг
    - Пятница
    - Суббота
    - Воскресенье
  text_formatting: 'bold' # форматирование текста: жирный шрифт
currency_settings:
  currency_symbol: '₽' # символ валюты: рубль
  decimal_places: 2 # количество знаков после запятой: два
other_settings:
  time_zone: 'Europe/Moscow' # часовой пояс: Москва
