server:
  port: 8080

database:
  url: jdbc:postgresql://localhost:5432/clever_bank
  username: postgres
  password: root
  driver-class-name: org.postgresql.Driver
  max-connection: 30
  min-connection: 10

profiles: en
